import type { Metadata } from "next";
import "./globals.css";
import SessionProviderWrapper from "@/components/wrappers/SessionProviderWrapper";
import Header from '@/components/header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProviderWrapper>
          <Header />
          <main className="mt-14 h-[calc(100vh-56px)]">
            {children}
          </main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
